# Generated by Django 6.0.4 on 2026-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['merchant', 'key', 'expires_at'], name='ledger_idem_merchan_0ec623_idx'),
        ),
    ]
